name: Sync from Gitee

on:
  schedule:
    - cron: '0 * * * *'  # 每小时同步一次
  workflow_dispatch:      # 支持手动触发

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      # Checkout GitHub 仓库
      - name: Checkout GitHub repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true  # 保证 push 使用 token

      # 配置 Git 用户信息（用于 merge commit）
      - name: Configure git
        run: |
          git config --global user.name "sync-bot"
          git config --global user.email "sync-bot@example.com"

      # 添加 Gitee remote
      - name: Add Gitee remote
        run: |
          git remote remove gitee || true
          git remote add gitee https://gitee.com/qwxrepo/natun.git

      # 拉取 Gitee 仓库
      - name: Fetch from Gitee
        run: git fetch gitee

      # 检查是否有更新并 merge + push
      - name: Merge and Push if updates exist
        run: |
          LOCAL=$(git rev-parse HEAD)
          REMOTE=$(git rev-parse gitee/master)
          if [ "$LOCAL" != "$REMOTE" ]; then
              echo "New commits detected from Gitee. Merging..."
              git merge gitee/master --allow-unrelated-histories -X theirs -m "sync from gitee"
              git push origin master
          else
              echo "No updates from Gitee. Skip merge and push."
          fi
